name: "transfer-app"

services:
  identity-app:
    container_name: identity-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${IG_GRPC_PORT:-50051}:50051'
    depends_on:
      - identity-db
    networks:
      - identity-network
    working_dir: /app
    volumes:
      - .:/app

  identity-db:
    container_name: identity-db
    restart: always
    image: 'postgres:16.2'
    ports:
      - '${IG_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${IG_DB_USER:-username}
      POSTGRES_PASSWORD: ${IG_DB_PASSWORD:-password}
      POSTGRES_DB: ${IG_DB_DATABASE:-identity-db}
    volumes:
      - identity-data:/var/lib/postgresql/data:rw
    networks:
      - identity-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${IG_DB_USER:-username} -d ${IG_DB_DATABASE:-identity-db}'"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  identity-data:
    driver: local

networks:
  identity-network:
    driver: bridge
